name: Workee-frontend
region: nyc
static_sites:
  - build_command: |-
      npm install
      npm run prod
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: irfdev/workee-frontend
    name: Workee-frontend
    error_document: index.html
    routes:
      - path: /
